controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app.swagger_ui:
    path: /api/doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }

api_app_login_check:
    path: /api/app/login_check
api_customer_login_check:
    path: /api/customer/login_check
api_admin_login_check:
    path: /api/admin/login_check